# Generated by Django 3.0.1 on 2020-01-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200102_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
