# Generated by Django 3.0.1 on 2020-01-02 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20200102_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
