# Generated by Django 3.0.1 on 2020-01-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0004_stat_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stat',
            name='last_value',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='stat',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribed_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
